version: "3"

# Adjusted Local Images version in favour of DockerHub hosted Images

services:
  database:
    container_name: database
    image: bazmurphy/cloud-tracker-database:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: bazmurphy/cloud-tracker-backend:latest
    depends_on:
      - database
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - DB_SSL=${DB_SSL}
      - AWS_CLOUDWATCH_REGION=${AWS_CLOUDWATCH_REGION}
      - AWS_CLOUDWATCH_ACCESS_KEY_ID=${AWS_CLOUDWATCH_ACCESS_KEY_ID}
      - AWS_CLOUDWATCH_SECRET_ACCESS_KEY=${AWS_CLOUDWATCH_SECRET_ACCESS_KEY}
    ports:
      - "4000:4000"

  frontend:
    container_name: frontend
    image: bazmurphy/cloud-tracker-frontend:latest
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  database-data:
