apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cloud-tracker
  name: backend-deployment
# spec defines the desired state of the Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  # we define the Pod template
  template:
    metadata:
      labels:
        app: backend
    # the container spec where we define the container(s)
    spec:
      containers:
        - name: backend
          image: bazmurphy/cloud-tracker-backend
          ports:
            - containerPort: 4000
          env: # get environment variables
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef: # from secret
                  name: database-secret
                  key: database-connection-string
            - name: DB_SSL
              valueFrom:
                configMapKeyRef: # from configMap
                  name: database-configmap
                  key: database-ssl
