apiVersion: v1
kind: Secret
metadata:
  namespace: cloud-tracker
  name: database-secret
type: Opaque # the Secret can contain any kind of data and is not specifically structured/interprted by Kubernetes
data: # here we define the Secret data
  postgres-password: cGFzc3dvcmQ= # in base64 encoded
  database-connection-string: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQGRhdGFiYXNlL2Nsb3VkdHJhY2tlcg== # in base64 encoded
