# edit to trigger deploy

name: Build and Deploy Backend on EC2

on:
  push:
    branches:
      - main
    # The workflow should trigger only on changes in the "backend" folder
    # paths:
    #   - "backend/**"

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    # run all the steps in the backend directory
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build Backend
        run: npm run build

      - name: SSH into EC2 > delete all pm2 processes > Clear api folder
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pwd &&
            ls -la &&
            pm2 list | grep -q "cloudtrackerapi" && pm2 delete all || true &&
            rm -rf api &&
            mkdir api &&
            ls -la

      - name: Check the contents of working directory (debug)
        run: ls -la

      - name: SCP dist to api folder
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend/dist/*"
          target: "api/"

      - name: SSH into EC2 > Start pm2 process (with injected db connection string)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pwd &&
            ls -la &&
            cd api &&
            pwd &&
            ls -la &&
            pm2 start index.js --name cloudtrackerapi --env DB_CONNECTION_STRING="${{ secrets.DB_CONNECTION_STRING }}"
