name: Build and Deploy Backend on EC2

on:
  push:
    branches:
      - main
    # The workflow should trigger only on changes in the "backend" folder
    paths:
      - "backend/**"

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    # run all the steps in the backend directory
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build Backend
        run: npm run build

      - name: EC2 SSH > Delete the PM2 process > Delete the /cloudtracker/ folder
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pm2 list | grep -q "cloudtrackerapi" && pm2 delete all || true &&
            rm -rf cloudtracker

      # - name: Check the contents of working directory (debug)
      #   run: ls -la

      - name: EC2 SCP > Copy /backend/dist to /cloudtracker/backend/dist
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend/*"
          target: "cloudtracker/"

      - name: EC2 SSH > Start PM2 process (with injected db connection string)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            DB_CONNECTION_STRING="${{ secrets.DB_CONNECTION_STRING }}" pm2 start "cloudtracker/backend/dist/index.js" --name cloudtrackerapi
