name: Build and Deploy Backend on EC2

on:
  push:
    branches:
      - main
    # The workflow should trigger only on changes in the "backend" folder
    # paths:
    #   - "backend/**"

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    # run all the steps in the backend directory
    defaults:
      run:
        working-directory: ./backend

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: cloudtracker
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Seed PostgreSQL Database
        run: npm run seed
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: cloudtracker

      - name: Test Backend
        env:
          DB_CONNECTION_STRING: "postgresql://postgres:password@localhost:5432/cloudtracker"
          DB_SSL: "false"
        run: npm run test

      - name: Build Backend
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_EC2 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_EC2 }}
          aws-region: us-east-1

      - name: Copy then Run "deploy-backend.sh" Script on EC2
        env:
          INSTANCE_ID: ${{ secrets.INSTANCE_ID_EC2 }}
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
          DB_SSL: "true"
        # ssm requires a policy on the ec2 instance
        run: |
          aws ssm send-command \
            --instance-ids $INSTANCE_ID_EC2 \
            --document-name "AWS-RunShellScript" \
            --comment "Copy script from repo" \
            --parameters commands=["cp ./.github/workflows/deploy-backend.sh . && chmod +x deploy-backend.sh && ./deploy-backend.sh -DB_CONNECTION_STRING=$DB_CONNECTION_STRING -DB_SSL=$DB_SSL"]
