name: Build and Deploy

on:
  push:
    branches:
      - main
    # The workflow should trigger only for changes in the "frontend" folder
    paths:
      - "frontend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Change to Frontend Directory
        run: cd frontend

      - name: Install Dependencies
        # run: npm install
        # npm ci = clean install
        run: npm ci

      - name: Build Frontend
        run: npm run build

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync to AWS S3
        run: aws s3 sync ./dist s3://bazmurphy-cloud-tracker
